server:
  port: ${PORT:8081}

spring:
  application:
    name: monolith-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projectdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    ignore-missing-migrations: true

jwt:
  public-key-path: classpath:keys/public.pem

logging:
  level:
    com.projectmanager: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
